// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcHVJ-I2BTIpZ5qsGsJT9_Q-RzfoHWQc0',
    authDomain: 'vetapp-1777a.firebaseapp.com',
    projectId: 'vetapp-1777a',
    storageBucket: 'vetapp-1777a.firebasestorage.app',
    messagingSenderId: '15654861042',
    appId: '1:15654861042:web:06daa214fff1ca8185386b',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcHVJ-I2BTIpZ5qsGsJT9_Q-RzfoHWQc0',
    appId: '1:15654861042:android:06daa214fff1ca8185386b',
    messagingSenderId: '15654861042',
    projectId: 'vetapp-1777a',
    storageBucket: 'vetapp-1777a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcHVJ-I2BTIpZ5qsGsJT9_Q-RzfoHWQc0',
    appId: '1:15654861042:ios:06daa214fff1ca8185386b',
    messagingSenderId: '15654861042',
    projectId: 'vetapp-1777a',
    storageBucket: 'vetapp-1777a.firebasestorage.app',
    iosBundleId: 'com.salma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcHVJ-I2BTIpZ5qsGsJT9_Q-RzfoHWQc0',
    appId: '1:15654861042:ios:06daa214fff1ca8185386b',
    messagingSenderId: '15654861042',
    projectId: 'vetapp-1777a',
    storageBucket: 'vetapp-1777a.firebasestorage.app',
    iosBundleId: 'com.salma.vetementIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcHVJ-I2BTIpZ5qsGsJT9_Q-RzfoHWQc0',
    appId: '1:15654861042:web:06daa214fff1ca8185386b',
    messagingSenderId: '15654861042',
    projectId: 'vetapp-1777a',
    authDomain: 'vetapp-1777a.firebaseapp.com',
    storageBucket: 'vetapp-1777a.firebasestorage.app',
  );
}
